### PR TITLE
docs: added data from keka portal into knowledge_base.csv

### LINKED ISSUE #8: [OTHER] Gather data
### What would you like to share?

- Gather HR Queries from pursuit employees
- Add data in `./src/knowledge_base.csv`
- Maintain the given format
- Read the company related documents in keka portal

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Tamalika89**
# Issue #8 📐

- I [Tamalika Day](https://github.com/Tamalika89) have worked for #8

## Guidelines 🔐

I accept the fact that I have followed the guidelines and have not copied the codes from around the internet

- [x] **Contribution Guidelines**
- [x] **Code of Conduct**

## Issue to be closed 🛅

- My pull request closes #8

## Screenshots 📷

Here are the pictures of changes that I have made 🔽

work_progress
work_progress2

  
  
  
---

### CODE REVIEW

**Comment by warmachine028** [comment]
@Tamalika89 please follow conventional commits to make PR titles

**Review by warmachine028 — CHANGES_REQUESTED** [review]
Add screenshot of the task you did in the Pull Request template where it is asked to submit Pull Requests,
You can edit the Template

**Comment by Tamalika89** [comment]
work_progress

**Review by warmachine028 — APPROVED** [review]
ok

**Pull request merged**
